"""
Django settings for student_union project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# 改为绝对导入, 从 CMS_mixins 文件夹中导入 CMS_utils
from CMS_mixins import CMS_utils

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pgs68)47-z#uhn8t288el0co1dx#9@r0n%n77ep4t@mv8)u7lg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user_system',
    'club_system',
    'notification_system',
    'event_system',
    'news_system.apps.NewsSystemConfig',
    'forum_system.apps.ForumSystemConfig',
    'club_hub',
    "corsheaders",  # 允许跨域请求
    "rest_framework",
    'message_system',
    "admin_system",
]

INSTALLED_APPS += ('django_summernote', ) # RTE 新的富文本编辑器

AUTH_USER_MODEL = 'user_system.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',

]

ROOT_URLCONF = 'student_union.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notification_system.views.base_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'student_union.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),  
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



if DEBUG:
    # 开发环境下使用本地存储

    # DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
    CSRF_TRUSTED_ORIGINS = ['https://localhost:8000']
else:
#     # 生产环境下使用 Amazon S3 存储
#     DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
#     AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
#     AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
#     AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
#     AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME')
#     AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
#     MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'
    CSRF_TRUSTED_ORIGINS = ['https://example.com']


# SUMMERNOTE_THEME = 'bs5'  # Show summernote with Bootstrap 5 theme

SUMMERNOTE_CONFIG = {
    # 开启 iframe 模式。若改为 False 则使用 SummernoteInplaceWidget，
    # 此时需要自行加载 Bootstrap/jQuery 的依赖。
    'iframe': False,

    # summernote 的基础设置
    'summernote': {
        'airMode': False,  # 是否使用 Air-mode
        'width': '100%',   # 编辑器宽度
        'height': '480',   # 编辑器高度
        # 默认语言，如果留空则自动匹配浏览器语言
        'lang': None,  
        # 自定义工具栏
        # 'toolbar': [
        #     ['style', ['style']],
        #     ['font', ['bold', 'underline', 'clear']],
        #     ['fontname', ['fontname']],
        #     ['color', ['color']],
        #     ['para', ['ul', 'ol', 'paragraph']],
        #     ['table', ['table']],
        #     ['insert', ['link', 'picture', 'video']],
        #     ['view', ['fullscreen', 'codeview', 'help']],
        # ],
    },

    'attachment_require_authentication': True,
    'disable_attachment': False,
    'attachment_absolute_uri': False,

    'lazy': True,
    'attachment_upload_to': CMS_utils.RTEUploadUtils.upload_img_func,
}

LOGIN_URL = '/login/'