"""
Django settings for student_union project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from CMS_mixins import CMS_utils

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pgs68)47-z#uhn8t288el0co1dx#9@r0n%n77ep4t@mv8)u7lg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '51.21.191.188',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user_system',
    'club_system',
    'notification_system',
    'event_system',
    'news_system.apps.NewsSystemConfig',
    'forum_system.apps.ForumSystemConfig',
    'club_hub',
    "corsheaders",
    "rest_framework",
    'message_system',
    "admin_system",
]

INSTALLED_APPS += ('django_summernote', ) # RTE Rich text editor

AUTH_USER_MODEL = 'user_system.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'user_system.middleware.CSRFRefreshMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://51.21.191.188:3000",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

ROOT_URLCONF = 'student_union.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notification_system.views.base_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'student_union.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-gb'

TIME_ZONE = 'Europe/London'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),  
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_COOKIE_SECURE = False

if DEBUG:
    # Using local storage in a development environment

    # DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
    CSRF_TRUSTED_ORIGINS = [
        "http://51.21.191.188:3000",
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:8000"]
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
#     # Using Amazon S3 Storage in a Production Environment
#     DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
#     AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
#     AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
#     AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
#     AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME')
#     AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
#     MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'
    CSRF_TRUSTED_ORIGINS = [
        "http://51.21.191.188:3000",
        "http://localhost:3000",
        "http://127.0.0.1:3000"]


# SUMMERNOTE_THEME = 'bs5'  # Show summernote with Bootstrap 5 theme

SUMMERNOTE_CONFIG = {
    # Enable iframe mode. If you change it to False, you will use the SummernoteInplaceWidget.
    # At this point, you need to load the Bootstrap/jQuery dependencies yourself.
    'iframe': False,

    # Basic settings for summernote
    'summernote': {
        'airMode': False,  # Whether to use Air-mode
        'width': '100%',   # Editor width
        'height': '480',   # Editor Height
        # Default language, automatically matches browser language if left blank
        'lang': None,  
        # Customized toolbars
        # 'toolbar': [
        #     ['style', ['style']],
        #     ['font', ['bold', 'underline', 'clear']],
        #     ['fontname', ['fontname']],
        #     ['color', ['color']],
        #     ['para', ['ul', 'ol', 'paragraph']],
        #     ['table', ['table']],
        #     ['insert', ['link', 'picture', 'video']],
        #     ['view', ['fullscreen', 'codeview', 'help']],
        # ],
    },

    'attachment_require_authentication': True,
    'disable_attachment': False,
    'attachment_absolute_uri': False,

    'lazy': True,

    'attachment_upload_to': CMS_utils.RTEUploadUtils.upload_img_func,
}

LOGIN_URL = '/login/'

# Customizing the CSRF Failure View
CSRF_FAILURE_VIEW = 'user_system.views.csrf_failure'