# Generated by Django 5.1.2 on 2025-01-31 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Club',
            new_name='Clubs',
        ),
    ]
