# Generated by Django 5.1.2 on 2025-02-06 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(default='#ffffff', max_length=100)),
                ('layout_mode', models.CharField(choices=[('grid', '网格布局'), ('free', '自由布局')], default='grid', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='customization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club_system.clubcustomization'),
        ),
        migrations.CreateModel(
            name='WidgetInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(max_length=50)),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('width', models.IntegerField(default=4)),
                ('height', models.IntegerField(default=4)),
                ('config', models.JSONField(default=dict)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='club_system.club')),
            ],
        ),
    ]
