# Generated by Django 5.1.2 on 2025-02-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_system', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, default="This Club hasn't added a Description yet", null=True),
        ),
    ]
