# Generated by Django 5.1.2 on 2025-01-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_system', '0002_rename_club_clubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='club_id',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
