# Generated by Django 5.1.2 on 2025-02-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_system', '0003_alter_clubs_club_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Clubs',
        ),
    ]
