# Generated by Django 5.1.2 on 2025-02-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_system', '0002_clubcustomization_club_customization_widgetinstance'),
        ('club_system', '0003_alter_club_description'),
    ]

    operations = [
    ]
