# Generated by Django 5.1.2 on 2025-02-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_system', '0004_merge_20250207_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='customization',
        ),
        migrations.RemoveField(
            model_name='widgetinstance',
            name='club',
        ),
        migrations.DeleteModel(
            name='ClubCustomization',
        ),
        migrations.DeleteModel(
            name='WidgetInstance',
        ),
    ]
