# Generated by Django 5.1.2 on 2025-02-04 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_system', '0005_membership_club_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='is_admin',
            new_name='is_manager',
        ),
    ]
