# Generated by Django 5.1.2 on 2025-02-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_system', '0006_newclubrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newclubrequest',
            name='id',
        ),
        migrations.AddField(
            model_name='newclubrequest',
            name='request_id',
            field=models.PositiveIntegerField(default=0, editable=False, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
