# Generated by Django 5.1.2 on 2025-02-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_system', '0007_remove_newclubrequest_id_newclubrequest_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newclubrequest',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
