# Generated by Django 5.1.2 on 2025-02-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_system', '0008_newclubrequest_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newclubrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=10),
        ),
    ]
