# Generated by Django 5.1.2 on 2025-03-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_system', '0009_alter_newclubrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='background_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
