# Generated by Django 5.1.2 on 2025-03-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_system', '0010_club_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
    ]
