# Generated by Django 5.1.2 on 2025-03-01 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_system", "0002_alter_category_id"),
        ("forum_system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blogPosts_event",
                to="event_system.event",
            ),
        ),
    ]
