# Generated by Django 5.1.2 on 2025-03-02 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum_system", "0002_blogpost_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="category",
            new_name="club",
        ),
    ]
