# Generated by Django 5.1.2 on 2025-02-18 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "club_system",
            "0005_remove_club_customization_remove_widgetinstance_club_and_more",
        ),
        ("forum_system", "0003_alter_blogpost_author_alter_comment_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blogPosts",
                to="club_system.club",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(),
        ),
    ]
