# Generated by Django 5.1.2 on 2025-01-28 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
        ("users", "__first__"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="leader",
            field=models.ForeignKey(
                help_text="The leader of the club.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leader_clubs",
                to="users.customuser",
            ),
        ),
        migrations.CreateModel(
            name="ClubRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_requests",
                        to="users.customuser",
                    ),
                ),
            ],
        ),
    ]
