# Generated by Django 5.1.2 on 2025-02-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('event_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
