# Generated by Django 5.1.2 on 2025-02-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General Messages'), ('approval', 'Club Approval'), ('event', 'Event Reminder'), ('news', 'News Update')], default='general', max_length=20),
        ),
    ]
