# Generated by Django 5.1.2 on 2025-02-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_system', '0003_notification_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Title', max_length=255),
            preserve_default=False,
        ),
    ]
