# Generated by Django 5.1.2 on 2025-02-13 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club_system', '0005_remove_club_customization_remove_widgetinstance_club_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=1)),
                ('height', models.IntegerField(default=1)),
                ('data', models.JSONField(default=dict)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='club_system.club')),
            ],
        ),
    ]
