# Generated by Django 5.1.2 on 2025-03-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('text', '文本'), ('chart', '图表'), ('notice', '公告'), ('image', '图片'), ('countdown', '倒计时')], default='text', max_length=20, verbose_name='组件类型'),
        ),
    ]
