# Generated by Django 5.1.2 on 2025-03-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_hub', '0002_widget_widget_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('text', '文本'), ('chart', '图表'), ('notice', '公告'), ('image', '图片'), ('countdown', '倒计时'), ('clock', '时钟'), ('event_selector', '活动')], default='text', max_length=20, verbose_name='组件类型'),
        ),
    ]
